### ISSUE TITLE
Latest Version of AF causes some items from Better End to be Invisible

### ISSUE THREAD

**Issue by aisukuma** [finallion/Artificial_Foliage-FABRIC-#10]
Artificial Foliage version 1.8 for Fabric causes some items from Better End to be invisible. Using lower versions of AF does not cause the invisible items issue for Better End. I let paulevs know about the issue as well.

Mod List
- Architectury [2.3.22]
- Artificial Foliage [1.8]
- BCLib [0.3.0]
- Better End [0.11.0-pre]
- Cloth Config v4 [5.0.36]
- Fabric API [0.37.2+1.17]
- Mod Menu [2.0.2]
- Roughly Enough Items [6.0.267-alpha]

![2021-08-10_18 21 46](https://user-images.githubusercontent.com/22802219/128943384-aa7ada17-4f45-4f8e-a259-e892f53f3218.png)

**Comment by finallion** [comment]
Bug caused by BCLib. Should be fixed in the upcoming version.
