### ISSUE TITLE
[Incompatibility] The Graveyard &  Artificial Foliage

### ISSUE THREAD

**Issue by SylisMC** [finallion/Artificial_Foliage-FABRIC-#11]
These two mods conflict. 

**Artificial Foliage**
Artificial_Foliage_1.8_(FABRIC)_1.17-1.17.1.jar
https://www.curseforge.com/minecraft/mc-mods/artificial-foliage

**The Graveyard**
The_Graveyard_1.2_(FABRIC)_for_1.17-1.17.1.jar
https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric
https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric/issues/1

[latest.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/7050407/latest.log)

**Comment by finallion** [comment]
Hi, why do you think its a conflict? It seems like a mixin from Articial Foliage is doing weird stuff! 

Edit: I replaced the criticial mixin with something else in the newest version (1.9). That should fix your problem hopefully. Let me know!

**Comment by SylisMC** [comment]
Hey, i know its these two mods conflicting because i made a profile with only those two mods, and if you look at the log file, they are the only two mods on the modload list beside the normal fabric apis

Also. sorry about duplicate posting (Sleepy_CA is me), i didnt realize you were the same creator haha

**Comment by SylisMC** [comment]
Everything appears to be fine.. i see no issues. and the log looks clean from boot to load world
[latest.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/7068525/latest.log)

**Comment by finallion** [comment]
No problem! Glad to hear and thanks for reporting!
