### ISSUE TITLE
[Crash] Failed to connect to server (in singleplayer)

### ISSUE THREAD

**Issue by SylisMC** [finallion/Artificial_Foliage-FABRIC-#12]
This might be the related to [issue 8](https://github.com/finallion/Artificial_Foliage-FABRIC-/issues/8) 

There is a weird crash happening when loading into or creating a world. you get the normal loading screen, get to 100% and then you get a black screen followed by this screen.. again this is a **SINGLE PLAYER** world. NOT a server
![image](https://user-images.githubusercontent.com/19602662/131174332-cfe7c445-e419-4aa4-804d-d1a5cd2f8967.png)

This same crash happens with a combination of mods
[latest.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/7068936/latest.log)
- [Artificial Foliage](https://www.curseforge.com/minecraft/mc-mods/artificial-foliage)
- [Chipped](https://www.curseforge.com/minecraft/mc-mods/chipped)

Leave this open for now because there are a LOT of combinations of mods that crash and im trying to figure out what combinations are causing this crash

**Comment by finallion** [comment]
Is this a fresh world? Looks like you have a lot of stuff going on in the logs. The error indicitates that the world is overloaded somehow. Doesn't really look like an issue with ARFO. The connection lost screen is nothing out of the ordinary, single player worlds also run on servers.

**Comment by SylisMC** [comment]
Yes, it doesn't matter if it's a fresh or existing world. same crash, but yes. it was a brand new world. i had this same issue in a different mod pack as well, without Chipped, and removing Artificial Foliage also fixed the issue. the same issue comes up with a multitude of mods, and removing artificial foliage seems to usually fix it. could it be an overload od blocks?

**Comment by finallion** [comment]
Yes, I was looking around in the fabric discord. Seems like this is a known issue and they are working on increasing the packet size. As you have quite a lot of mods which add tons of blocks and ARFO too adds a lot, this may be the issue. You can try https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric but it may not work.

I'm closing this as off right now, as there is not much I can do, sorry! Hope the XL Packet mod will help you!

**Comment by SylisMC** [comment]
Sorry. i didnt notice the response, thanks for linking me that
