### ISSUE TITLE
Log shows mod failing to load from non-installed mods

### ISSUE THREAD

**Issue by katubug** [finallion/Artificial_Foliage-FABRIC-#14]
Hi! I'm sorry that I can't provide a copy of my log atm because I'm on my phone. I wanted to report this before I forgot!

Basically, near the beginning of loading, the log throws a bunch of errors about not finding BYG or BOP, presumably because I have neither installed. I'm guessing the mod doesn't have a check for whether those mods are loaded before it tries to access them? I'm not a modder, so that's just an educated guess.

Anyway, if you'd like the log, let me know and I'll get one uploaded ASAP! I'm also happy to provide any other information. Thank you!

**Comment by finallion** [comment]
Hey! The logs would be fantastic. Basically, there is no check for other mods. All blocks are loaded every time, independent if BYG or BOP is present. And the blocks too, are independent from these mods. Some updates ago I removed a bunch of recipes. This could show up in the logs...

**Comment by katubug** [comment]
[latest.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/7106057/latest.log)
So the log itself has a ton of errors that I'm working on isolating (idk why so many of them are for mods I don't even have! like what the hell is gbuffer?), which means it's huge.

Here is an excerpt with the relevant lines: https://pastebin.com/2NJMsid6

Although looking through it again this morning, it seems like it'd be more likely some kind of terrain gen mod? So this may be a total false alarm, in which case I apologize!

**Comment by finallion** [comment]
Thats quite the log you got there... I'm unable to tell what is going on, but you have a ton a incompatible mods and you are mixing fabric with forge mods like botania and the forge version of byg. Addtionally is seems you're combining 1.16 with 1.17 mods. Some of the ongoing stuff breaks all recipes (and like it seems a lot more) in game, even the minecraft vanilla ones. 
I'm closing this one as it is not ARFO breaking stuff but something breaking ARFO (and a lot of other mods). It just says recipes from ARFO are not being loaded, again, all recipes seem to be not loading

**Comment by katubug** [comment]
That's exactly what I mean when I say it's referencing mods I don't even
have. I don't HAVE Botania or BYG. All of my mods were assembled using the
Curseforge launcher, so they're all fabric and 1.17+. I don't know what
gbuffer shaders even is. And the weirdest part is that the game runs just
fine, no crashes and no major bugs that I've seen so far. There's rarely
anything in my server or client logs while playing. So I dunno. I obviously
would like to get these things sorted out, hence the report, but since the
logs don't actually tell me anything terribly concrete about what mod is
actually causing the problems, I have had little luck so far.

Anyway, thank you for your time. I apologize again for the false alarm!
