### ISSUE TITLE
Turn off compatibility blocks when related mod is not present.

### ISSUE THREAD

**Issue by Zarepheth** [finallion/Artificial_Foliage-FABRIC-#17]
Although the mod pack I'm using and the additional mods I've added do not include Biomes O'Plenty (BOP), Traverse, or Biomes You'll Go (BYG), this mod still adds the related blocks to the game and spams the Roughly Enough Items (REI) list of target blocks I could craft.

Is there a configuration option to turn off those blocks?
If not, can the mod itself detect the presence (or absence) of the other mods and only turn on related blocks if the other mod is present?

**Comment by finallion** [comment]
Hi! The mod doesn't work with compatibility. All the blocks (even the byg, bop, traverse ones) are part of the basic mod. Currently there is no way to disable part of the blocks.
