### ISSUE TITLE
1.17 Server crash

### ISSUE THREAD

**Issue by EerieP** [finallion/Artificial_Foliage-FABRIC-#2]
Server seems to crash when a user connects. Running a custom mod pack. Seems to work fine in singleplayer. Attached is both log files from server and client.
[latest_server.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/6706022/latest_server.log)
[latest_client.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/6706023/latest_client.log)

**Comment by finallion** [comment]
Thanks for reporting and sorry for the inconvinience! 
Fixed the recipe jsonSyntaxException in the latest version (1.2) - I didn't notice mojang changed the name from "azalea_leaves_flowers" to "flowering_azalea_leaves". But I'm not sure if this is causing the server to crash. It seems that you have a chunk on your server with quite a bit of data (too many entites, tags etc.) in it, causing the "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 2174377, should be less than 2097152): net.minecraft.class_2788@7bfa3755" - you might check on that.

**Comment by EerieP** [comment]
> Thanks for reporting and sorry for the inconvinience!
> Fixed the recipe jsonSyntaxException in the latest version (1.2) - I didn't notice mojang changed the name from "azalea_leaves_flowers" to "flowering_azalea_leaves". But I'm not sure if this is causing the server to crash. It seems that you have a chunk on your server with quite a bit of data (too many entites, tags etc.) in it, causing the "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 2174377, should be less than 2097152): net.minecraft.class_2788@7bfa3755" - you might check on that.

Thank you for the quick response and fix! Awesome mod btw. I kinda figured that extra bit was about the server being too big. heh

**Comment by EerieP** [comment]
This seems to still be happening in ArFo 1.3
Server logs: [2021-06-27-6.log.gz](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/6722214/2021-06-27-6.log.gz)

**Comment by finallion** [comment]
hm. The warnings about "Ignored advancement" are just happening, because I removed these recipes. They can be ignored. The problem is Mojangs advancement loading. When a player has unlocked too many recipes, it can crash the server. I'll will delete some recipe advancements in the future version and hope people use REI... There is also a mod which improves the algorithm of minecraft advancement loading - Advancement Debug; this might help you. Sorry that I cant do more atm!

**Comment by finallion** [comment]
> This seems to still be happening in ArFo 1.3
> Server logs: [2021-06-27-6.log.gz](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/6722214/2021-06-27-6.log.gz)

In the 1.4 version I removed the recipe advancements completly. Maybe this will help .... !
